# This has path set explicitly temporarily in case this is running as part of the first time execution and the path hasnt updated to include go
- shell:
    - PATH=$PATH:/usr/local/go/bin go install mvdan.cc/sh/v3/cmd/shfmt@latest

- create:
    - ~/.local/bin

- link:
    ~/.local/bin/shfmt: ~/go/bin/shfmt
