# update ubuntu dock with default preferred shortcuts
- shell:
    - gsettings set org.gnome.shell favorite-apps "['firefox_firefox.desktop', 'thunderbird_thunderbird.desktop', 'org.gnome.Nautilus.desktop', 'code_code.desktop', 'org.gnome.Terminal.desktop', 'spotify_spotify.desktop', 'bitwarden_bitwarden.desktop']"
    - dconf load /org/gnome/terminal/legacy/profiles:/ < gnome-terminal-profiles.dconf
    - gsettings set org.gnome.desktop.background picture-uri "file://$(realpath ".")/wallpaper.jpg"
    - gsettings set org.gnome.desktop.background picture-uri-dark "file://$(realpath ".")/wallpaper.jpg"
    - gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
    - gsettings set org.gnome.desktop.interface icon-theme "Yaru-viridian"
    - gsettings set org.gnome.desktop.interface gtk-theme "Yaru-viridian-dark"
