# This has path set explicitly temporarily in case this is running as part of the first time execution and the path hasn't updated to include go
- shell:
    - PATH=$PATH:/usr/local/go/bin go install github.com/google/yamlfmt/cmd/yamlfmt@latest

- create:
    - ~/.local/bin

- link:
    ~/.local/bin/yamlfmt: ~/go/bin/yamlfmt
