# install oh my zsh if its not already present.
# this will not change the shell automatically. shell change is handled in another config intended to be run with root access.
- if:
    cond: if [ -z $ZSH ] && [ ! -d /home/$USER/.oh-my-zsh ]; then exit 0; else exit 1;fi
    met:
      - shell:
          - sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    unmet:
      - shell:
          - echo ZSH already seems to be installed. skipping

- git:
    '~/.oh-my-zsh/custom/plugins/zsh-autosuggestions':
      url: 'https://github.com/zsh-users/zsh-autosuggestions'
      description: 'oh my zsh - autosuggestions'
    '~/.oh-my-zsh/custom/themes/powerlevel10k':
      url: 'https://github.com/romkatv/powerlevel10k.git'
      description: 'oh my zsh - powerlevel10k'
    '~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting':
      url: 'https://github.com/romkatv/zsh-syntax-highlighting.git'
      description: 'oh my zsh - syntax highlighting'

- link:
    ~/.zshrc: shell/zsh/zshrc
    ~/.p10k.zsh: shell/zsh/p10k.zsh
