set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @yank_with_mouse on
set -g @yank_selection 'clipboard'
set -g @yank_selection_mouse 'clipboard'
set -g @yank_action 'copy-pipe-no-clear'

# Prefix
unbind C-b
set-option -g prefix C-Space
bind C-Space send-prefix

# Splits
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Windows
setw -g automatic-rename on
set -g renumber-windows on
set -g base-index 1
set -g pane-base-index 1

# Reload
unbind r
bind r source-file ~/.tmux.conf

# Mouse
set -g mouse on

bind -n WheelUpPane \
    if-shell -F '#{mouse_any_flag}' \
        'send-keys -M' \
        'if-shell -F "#{alternate_on}" "send-keys -M" "copy-mode -e; send-keys -M"'

bind -n WheelDownPane \
    if-shell -F '#{mouse_any_flag}' \
        'send-keys -M' \
        'if-shell -F "#{alternate_on}" "send-keys -M" "send-keys -M"'

# Copy mode
set -g mode-keys vi
set -g allow-passthrough on
set -g set-clipboard on

unbind p
bind p paste-buffer
unbind v
bind v copy-mode

unbind -T copy-mode-vi Space
unbind -T copy-mode-vi Enter
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi r send-keys -X rectangle-toggle

# History
set-option -g history-limit 50000

# Activity
set-window-option -g monitor-activity on
set-option -g visual-activity on

# Pane navigation
unbind l
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Pane resize
bind -r H resize-pane -L
bind -r J resize-pane -D
bind -r K resize-pane -U
bind -r L resize-pane -R

# Repeat time
set -g repeat-time 1000

# Terminal
set -g default-terminal "tmux-256color"
set -ga terminal-features ",tmux-256color:RGB,xterm-256color:RGB"
set -ga terminal-overrides ",tmux-256color:Tc,xterm-256color:Tc"

run '~/.tmux/plugins/tpm/tpm'