- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ['~', '~/.config']

# bootstrap installs
- shell:
  - sudo apt install curl
  - sudo apt install zsh
  # command requires i/o to work - cant input password without stderr
  - 
    command: chsh -s $(which zsh)
    stdin: true
    stdout: true
    stderr: true
  - sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# link dotfiles
- link:
    ~/.bashrc: bashrc
    ~/.tmux.conf: tmux.conf
    ~/.zshrc: zshrc
    