---
- defaults:
    link:
      create: true
      relink: true
      force: true
    shell:
      stdin: true
      stdout: true
      stderr: true
    snap:
      classic: false # default

- clean: ['~', '~/.config']

# install oh my zsh. this will not change the shell automatically (that is done later to save time on password injection)
- if:
    cond: if [ -z $ZSH ] && [ ! -d /home/$USER/.oh-my-zsh ]; then exit 0; else exit 1;fi
    met:
      - shell:
          - sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    unmet:
      - shell:
          - echo ZSH already seems to be installed. skipping

# bootstrap installs and shell
- sudo:
    - apt:
        - curl
        - zsh
        - tmux
        - build-essential
        - xclip
        - cmake
        - gitk
        - timewarrior

    - snap:
        - spotify:
        - code:
          classic: true
        - slack:
        - discord:
        - nvim:
          classic: true
        - bitwarden:

    # change to zsh for the user running the script
    - shell:
        - chsh -s $(which zsh) "$SUDO_USER"

# install auto suggestions for oh my zsh
- git:
    '~/.oh-my-zsh/custom/plugins/zsh-autosuggestions':
      url: 'https://github.com/zsh-users/zsh-autosuggestions'
      description: 'oh my zsh - autosuggestions'
    '~/.oh-my-zsh/custom/themes/powerlevel10k':
      url: 'https://github.com/romkatv/powerlevel10k.git'
      description: 'oh my zsh - powerlevel10k'
    '~/.oh-my-zsh/custom/themes/zsh-syntax-highlighting':
      url: 'https://github.com/romkatv/zsh-syntax-highlighting.git'
      description: 'oh my zsh - syntax highlighting'

# link dotfiles
- link:
    ~/.bashrc: bashrc
    ~/.tmux.conf: tmux.conf
    ~/.zshrc: zshrc
    ~/.config/nvim:
      create: true
      path: nvim
    ~/.p10k.zsh: p10k.zsh

# default git config
- shell:
    - git config --global core.editor "nvim"
    - git config --global user.name "Lucien Morey"
    - git config --global init.defaultBranch main

# update ubuntu dock with default preferred shortcuts
- shell:
    - gsettings set org.gnome.shell favorite-apps "['firefox_firefox.desktop', 'thunderbird_thunderbird.desktop', 'org.gnome.Nautilus.desktop', 'code_code.desktop', 'org.gnome.Terminal.desktop', 'spotify_spotify.desktop', 'bitwarden_bitwarden.desktop']"
