- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ['~', '~/.config']

# bootstrap installs
- shell:
  - sudo apt install curl
  - sudo apt install zsh
  - sudo apt install tmux
  
  # command requires i/o to work - cant input password without stderr
  - 
    command: chsh -s $(which zsh)
    stdin: true
    stdout: true
    stderr: true
  # this needs to be tested properly
  - sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  

# link dotfiles
- link:
    ~/.bashrc: bashrc
    ~/.tmux.conf: tmux.conf
    ~/.zshrc: zshrc
    ~/.config/nvim:
      create: true
      path: nvim

- shell:
  - echo run the following to add autosuggestions to zsh
  - echo git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH_CUSTOM/plugins/zsh-autosuggestions
