- defaults:
    link:
      create: true
      relink: true
      force: true
    shell:
      stdin: true
      stdout: true
      stderr: true
    snap:
      classic: false # default

- clean: ['~', '~/.config']

# bootstrap installs
- sudo:
  - apt:
    - curl
    - zsh
    - tmux
    - build-essential

  - snap:
    - spotify:
    - cmake:
      - classic: true
    - nvim:
      - classic: true
    - code:
      - classic: true
    - slack:
      - classic: true

# install oh my zsh
- shell:
  # this needs to be tested properly
  - RUNZSH=no sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# install auto suggestions for oh my zsh
- git:
    '~/.oh-my-zsh/custom/plugins/zsh-autosuggestions':
        url: 'https://github.com/zsh-users/zsh-autosuggestions'
        description: 'oh my zsh - autosuggestions'

# link dotfiles
- link:
    ~/.bashrc: bashrc
    ~/.tmux.conf: tmux.conf
    ~/.zshrc: zshrc
    ~/.config/nvim:
      create: true
      path: nvim
