- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ['~', '~/.config']

# bootstrap installs
- shell:
  - sudo apt install curl
  - sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# link dotfiles
- link:
    ~/.bashrc: bashrc
    ~/.tmux.conf: tmux.conf
    ~/.zshrc: zshrc
    