#!/usr/bin/env bash

set -e

CONFIG=".install.conf.yaml"
DOTBOT_DIR=".dotbot"
DOTBOT_PLUGIN_DIR=".dotbot_plugins"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"

git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" \
--plugin-dir "${DOTBOT_PLUGIN_DIR}/dotbot-apt" \
--plugin-dir "${DOTBOT_PLUGIN_DIR}/dotbot-git" \
--plugin-dir "${DOTBOT_PLUGIN_DIR}/dotbot-snap" \
--plugin-dir "${DOTBOT_PLUGIN_DIR}/dotbot-sudo" \
--plugin-dir "${DOTBOT_PLUGIN_DIR}/dotbot-if" \
"${@}"
